import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  // flowering plants
  {
    _id: uuid(),
    title: "Anthurium Red Mini Plant",
    imgSrc: "/images/products/anthurium-red-mini-plant-medium.jpg",
    price: 1100,
    discount: 1000,
    startRating: 4,
    size: "medium",
    inStock: true,
    fastDelivery: true,
    onSale: false,
    isFlower: true,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Kalanchoe Plant - Yellow",
    imgSrc: "/images/products/kalanchoe-plant-yellow.jpg",
    price: 400,
    discount: 300,
    startRating: 5,
    size: "small",
    inStock: true,
    fastDelivery: false,
    onSale: false,
    isFlower: true,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Peace Lily Plant",
    imgSrc: "/images/products/peace-lily-plant.jpg",
    price: 500,
    discount: 350,
    startRating: 5,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: true,
    isFlower: true,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Poinsettia Plant",
    imgSrc: "/images/products/red-poinsettia-plant.jpg",
    price: 700,
    discount: 650,
    startRating: 4.5,
    size: "medium",
    inStock: true,
    fastDelivery: false,
    onSale: false,
    isFlower: true,
    isFruit: false,
    isMedicinal: false,
    isIndoor: false,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Ixora (Rugmini) Plant - Yellow",
    imgSrc: "/images/products/ixora-rugmini-plant-yellow.jpg",
    price: 600,
    discount: 450,
    startRating: 3,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: true,
    isFlower: true,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Ixora (Rugmini) Plant - Orange",
    imgSrc: "/images/products/ixora-rugmini-plant-dark-orange.jpg",
    price: 700,
    discount: 550,
    startRating: 5,
    size: "medium",
    inStock: true,
    fastDelivery: true,
    onSale: false,
    isFlower: true,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Aechmea Fasciata Plant",
    imgSrc: "/images/products/aechmea-fasciata-plant.jpg",
    price: 400,
    discount: 250,
    startRating: 3,
    size: "medium",
    inStock: false,
    fastDelivery: false,
    onSale: false,
    isFlower: true,
    isFruit: false,
    isMedicinal: true,
    isIndoor: true,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Kalanchoe Plant - Red",
    imgSrc: "/images/products/kalanchoe-plant-orange.jpg",
    price: 600,
    discount: 500,
    startRating: 4,
    size: "small",
    inStock: false,
    fastDelivery: false,
    onSale: false,
    isFlower: true,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },

  // medicinal plants

  {
    _id: uuid(),
    title: "Aloe Vera Plant",
    imgSrc: "/images/products/aloe-vera-plant-medium.jpg",
    price: 1000,
    discount: 800,
    startRating: 5,
    size: "medium",
    inStock: true,
    fastDelivery: true,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: true,
    isIndoor: true,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Rosemary Plant",
    imgSrc: "/images/products/rosemary-plant.jpg",
    price: 700,
    discount: 500,
    startRating: 5,
    size: "medium",
    inStock: true,
    fastDelivery: true,
    onSale: false,
    isFlower: true,
    isFruit: false,
    isMedicinal: true,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },

  // fruits plants

  {
    _id: uuid(),
    title: "Kesar Mango Plant",
    imgSrc: "/images/products/kesar-mango-plant.jpg",
    price: 600,
    discount: 250,
    startRating: 5,
    size: "medium",
    inStock: true,
    fastDelivery: true,
    onSale: true,
    isFlower: false,
    isFruit: true,
    isMedicinal: false,
    isIndoor: false,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Sapota Plant (Chiku)",
    imgSrc: "/images/products/sapota-plant-(chiku).jpg",
    price: 500,
    discount: 300,
    startRating: 5,
    size: "medium",
    inStock: true,
    fastDelivery: false,
    onSale: false,
    isFlower: false,
    isFruit: true,
    isMedicinal: false,
    isIndoor: false,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },

  // outdoor plants

  {
    _id: uuid(),
    title: "Philodendron Melinonii Green",
    imgSrc: "/images/products/philodendron-melinonni-green.jpg",
    price: 500,
    discount: 300,
    startRating: 3,
    size: "medium",
    inStock: false,
    fastDelivery: true,
    onSale: false,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: false,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Thuja Plant",
    imgSrc: "/images/products/thuja-plant-xl.jpg",
    price: 1600,
    discount: 1300,
    startRating: 5,
    size: "medium",
    inStock: true,
    fastDelivery: true,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: false,
    isOutdoor: true,
    isClimber: false,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  
  // Office desk plants

  {
    _id: uuid(),
    title: "Haworthia Fasciata Plant",
    imgSrc: "/images/products/haworthia-fasciata-plant.jpg",
    price: 300,
    discount: 200,
    startRating: 3.5,
    size: "small",
    inStock: true,
    fastDelivery: false,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Green Fern Plant",
    imgSrc: "/images/products/green-fern-plant.jpg",
    price: 200,
    discount: 150,
    startRating: 4.5,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: false,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: true,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Earth Star Plant",
    imgSrc: "/images/products/earth-start-plant-pink.jpg",
    price: 400,
    discount: 200,
    startRating: 4.5,
    size: "small",
    inStock: false,
    fastDelivery: true,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: false,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Snake Plant - Golden",
    imgSrc: "/images/products/snake-plant-golden.jpg",
    price: 300,
    discount: 200,
    startRating: 4.7,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Haworthia Cymbiformis Plant",
    imgSrc: "/images/products/haworthia-cymbiformis-plant.jpg",
    price: 500,
    discount: 400,
    startRating: 5,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: false,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Radermachera Bonsai Plant",
    imgSrc: "/images/products/radermachera-bonsai-plant.jpg",
    price: 1200,
    discount: 1000,
    startRating: 5,
    size: "small",
    inStock: true,
    fastDelivery: false,
    onSale: false,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Money Plant Satin",
    imgSrc: "/images/products/money-plant-satin.jpg",
    price: 600,
    discount: 500,
    startRating: 4.5,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: false,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: true,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "The Sun-loving Succulent Bundle",
    imgSrc: "/images/products/the-sun-loving-succulent-bundle.jpg",
    price: 1500,
    discount: 1200,
    startRating: 3.5,
    size: "small",
    inStock: true,
    fastDelivery: false,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Haworthia Turgida Plant",
    imgSrc: "/images/products/haworthia-turgida.jpg",
    price: 200,
    discount: 100,
    startRating: 3.5,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: false,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "The TableTop Succulent Bundle",
    imgSrc: "/images/products/the-tabletop-succulent-bundle.jpg",
    price: 1200,
    discount: 900,
    startRating: 5,
    size: "small",
    inStock: true,
    fastDelivery: false,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Chlorophytum Spider Plant",
    imgSrc: "/images/products/chlorophytum-spider-plant.jpg",
    price: 700,
    discount: 500,
    startRating: 5,
    size: "small",
    inStock: false,
    fastDelivery: false,
    onSale: false,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "ZZ Plant",
    imgSrc: "/images/products/zz-plant.jpg",
    price: 600,
    discount: 500,
    startRating: 4.5,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Lucky Bamboo Plant",
    imgSrc: "/images/products/lucky-bamboo-plant.jpg",
    price: 500,
    discount: 400,
    startRating: 4.5,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: false,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: false,
    isTableTop: true,
    qty: 1,
    wishlist: false
  },

  // Climbers

  {
    _id: uuid(),
    title: "Betel Leaf Plant - (Magai Paan)",
    imgSrc: "/images/products/betel-leaf-plant-magai-paan.jpg",
    price: 800,
    discount: 700,
    startRating: 4.8,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: true,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Dragon Bubble Plant",
    imgSrc: "/images/products/dragon-bubble-plant.jpg",
    price: 500,
    discount: 400,
    startRating: 4.8,
    size: "small",
    inStock: false,
    fastDelivery: false,
    onSale: false,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: true,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Money Plant - Golden",
    imgSrc: "/images/products/money-plant-golden.jpg",
    price: 400,
    discount: 200,
    startRating: 3.8,
    size: "small",
    inStock: true,
    fastDelivery: false,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: true,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Philodendron Oxycardium Brasil",
    imgSrc: "/images/products/philodendron-oxycardium-brasil-with-hanging-pot.jpg",
    price: 600,
    discount: 500,
    startRating: 3.8,
    size: "small",
    inStock: true,
    fastDelivery: false,
    onSale: false,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: true,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Philodendron Oxycardium Green",
    imgSrc: "/images/products/philodendron-oxycardium-green-with-hanging-pot.jpg",
    price: 400,
    discount: 300,
    startRating: 4.2,
    size: "small",
    inStock: true,
    fastDelivery: false,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: true,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Twisted Hoya",
    imgSrc: "/images/products/twisted-hoya.jpg",
    price: 300,
    discount: 100,
    startRating: 3.5,
    size: "small",
    inStock: true,
    fastDelivery: true,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: true,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
  {
    _id: uuid(),
    title: "Money Plant Variegated",
    imgSrc: "/images/products/money-plant-variegated.jpg",
    price: 900,
    discount: 800,
    startRating: 4.3,
    size: "small",
    inStock: true,
    fastDelivery: false,
    onSale: true,
    isFlower: false,
    isFruit: false,
    isMedicinal: false,
    isIndoor: true,
    isOutdoor: false,
    isClimber: true,
    isTableTop: false,
    qty: 1,
    wishlist: false
  },
];
